### ISSUE TITLE
Missing website text

### ISSUE THREAD

**Issue by rolandschuetz** [rolandschuetz/sailing-website#10]
Hello Nikola,

please discuss this with Ignacio and put the text on the website.

http://new.sailing.hr/work-with-us -> AMASSADOR
 http://new.sailing.hr/our-yachts-> Payment text is wrong, there's no more bank wiring

**Comment by MonsieurS** [comment]
@rolandschuetz 
http://new.sailing.hr/our-yachts-> Payment text is wrong, there's no more bank wiring [Done]

**Comment by nikolaskarica** [comment]
http://new.sailing.hr/work-with-us -> AMASSADOR [DONE]
http://new.sailing.hr/our-yachts-> Payment text is wrong, there's no more bank wiring [Done]
