### ISSUE TITLE
Copy all page titles and descriptions from Wordpress to our Contao pages

### ISSUE THREAD

**Issue by rolandschuetz** [rolandschuetz/sailing-website#12]
Hallo Nikola,

currently the pages are all missing a description and the title sometimes is not correctly set. Please take the ones from Wordpress as far as they make sense.

http://screencast.com/t/EKUmyRyTJo

Thanks,
Roland

**Comment by MonsieurS** [comment]
On outdated pages put orange box on top of the page that says "This page is outdated, visit out new page" and link to home page

**Comment by MonsieurS** [comment]
Copied titles and descriptions of all pages that are currently styled and visible on Conatnao (Sailing.hr and Pink Armada).

Still need to copy rest of the pages which are not styled and visible.

**Comment by rolandschuetz** [comment]
Great!
