### ISSUE TITLE
Replace the old website week selection with the new one

### ISSUE THREAD

**Issue by rolandschuetz** [rolandschuetz/sailing-website#2]
- new styles
 - faster loading
 - more awesomeness

**Comment by MonsieurS** [comment]
- add cover images
- link buttons on correct week for booking
- link youtube videos

**Comment by rolandschuetz** [comment]
For YouTube-Links see here: https://github.com/rolandschuetz/sailing-website/issues/5

**Comment by rolandschuetz** [comment]
Hello @nikolaskarica, in the new layout your coded didn't work and break a lot of CSS wasn't so clean. In the future try to make a few html as possible. :)

It''s online at new.sailing.hr
