### ISSUE TITLE
admin@sailing.hr E-Mail Address

### ISSUE THREAD

**Issue by rolandschuetz** [rolandschuetz/sailing-website#26]
Hello Nikola,

for our HTTPS certificate we need one of those email addresses:
 - admin@saling.hr
- webmaster@sailing.hr

Please create one and make sure you can get these emails.

Thanks,
Roland

**Comment by MonsieurS** [comment]
email: admin@sailing.hr
pass: <Q8mD3 (last two letters are on facebook)
