### ISSUE TITLE
Forward and delete old emails

### ISSUE THREAD

**Issue by nikolaskarica** [rolandschuetz/sailing-website#27]
@rolandschuetz 
Can you forward these emails to info@sailing.hr and delete them
1. goga@sailing.hr
2. ivana@sailing.hr
3. martina@sailing.hr

You can access admin.google.com with admin@sailing.hr

**Comment by rolandschuetz** [comment]
Are you receiving emails for admin@sailing.hr or just me?

I guess if admin@sailing.hr is "my" email address the above should be redirected to your email address. If you are also reading the emails from admin@sailing.hr that's fine.

**Comment by MonsieurS** [comment]
These 3 listed email addressees should be forwarded to info@sailing.hr and that deleted. So poeple can still send emails to them.
We were talking about this with Tibor and Ignacio when Tibor suggested to make aliases of those emails and then delete them.
