### ISSUE TITLE
Layout broken on big screens in Firefox

### ISSUE THREAD

**Issue by rolandschuetz** [rolandschuetz/sailing-website#49]
![https://www.evernote.com/shard/s90/sh/673879e3-a3d2-43f5-812a-fe6133b7701c/400c440a23999d2b11658bf6f2eb778b](https://www.evernote.com/shard/s90/sh/673879e3-a3d2-43f5-812a-fe6133b7701c/400c440a23999d2b11658bf6f2eb778b/res/1db09afc-9849-4d5e-9ab2-1996fcf96329/skitch.png?resizeSmall&width=832)

**Comment by MonsieurS** [comment]
Have you tried deleting cache? Because I fixed images and that font

**Comment by rolandschuetz** [comment]
Seems to be already fixed
