### ISSUE TITLE
Update Week Selection YouTube Videos

### ISSUE THREAD

**Issue by rolandschuetz** [rolandschuetz/sailing-website#5]

**Comment by MonsieurS** [comment]
@rolandschuetz 
When you upload new week selection code I will link youtube videos and pictures to it

**Comment by rolandschuetz** [comment]
Can you please send me the list, because I need to add this to the shop as well

**Comment by MonsieurS** [comment]
Week 25 - http://youtu.be/r7C4bdti2gs
Week 26 - http://youtu.be/0UulEJo2bog
Week 27 - http://youtu.be/r8CodpKA8us
Week 28 - http://youtu.be/c6qVnVhvtvs
Week 29 - http://youtu.be/c6qVnVhvtvs
Week 30 - http://youtu.be/NhwoRh_iEc4
Week 31 - http://youtu.be/kVudbpMfyyc
Week 32 - http://youtu.be/kVudbpMfyyc
Week 33 - http://youtu.be/kIgFNuAWnjw
Week 34 - http://youtu.be/_WU01f35XHI

**Comment by rolandschuetz** [comment]
Updated in the shop and on the website
