### ISSUE TITLE
Additional cost issue with price and clicking

### ISSUE THREAD

**Issue by nikolaskarica** [rolandschuetz/sailing-website#51]
@rolandschuetz 
This is tested in IE11. There is an issue with price on additional cost and with clicking. When you click NO, price is still green and then you need to click again YES and then NO for price to go grey.
And the price for skipper changes when you pick skipper and hostess
![issue_additional_cost](https://cloud.githubusercontent.com/assets/6334510/6558059/f69de6b8-c679-11e4-95dc-38b389133f73.PNG)

**Comment by MonsieurS** [comment]
@rolandschuetz
